baseURL = "https://hwayne.github.io/alloy-hugo-demo"
languageCode = "en-us"
title = "alloy"
theme = "ananke"
Paginate = "40" # Number of posts per page

[permalinks]
# Probably temporary, get feedback of team
page = "/:filename/" #removes the /page/

[Params]
background_color_class = "bg-navy"
custom_css = ["custom.css"]
